trigger:
- main

variables:
  azureServiceConnection: 'azure_service_connection'
  terraformVersion: '1.10.1'
  backendResourceGroup: 'rg-qr-code'
  backendStorageAccountName: 'tfqrcode'

stages:
  - stage: "Terraform_Deployment"
    jobs:
      - job: "AKS_Deployment"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '$(terraformVersion)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory/product-infrastructure)'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccountName)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory/product-infrastructure)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: '$(azureServiceConnection)'
              workingDirectory: '$(System.DefaultWorkingDirectory/product-infrastructure)'
              commandOptions: '-out=tfplan'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory/product-infrastructure)'
              commandOptions: 'tfplan --auto-approve'
              environmentServiceName: '$(azureServiceConnection)'
              backendServiceArm: '$(azureServiceConnection)'
              backendAzureRmResourceGroupName: '$(backendResourceGroup)'
              backendAzureRmStorageAccountName: '$(backendStorageAccountName)'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'